services:
  - type: web
    name: wp-pomo-translator
    runtime: node
    plan: free
    region: frankfurt # یا oregon یا ohio
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # این مقدار را در پنل رندر به صورت Secret وارد کنید (اختیاری برای موتور جمینای)
